# <a id='toc1_'></a>[PCE:Couplage de rdkit ,xTB, Pyscf et  AlGORITHME DE SCHARBER( model de Tartarus)  ](#toc0_)

1. **MVOTO KONGO Patrick Sorrel**, sorrel.mvoto@facsciences-uy1.cm
    * Department of Physics, Faculty of Science, University of Yaounde I 
Etudiant de Master au Laboratoire de 
    * Physique Atomique Moleculaire et Biophysique

MAi 2024

### <a id='toc1_'></a>[Utilisation de Pandas  pour extraire les information dans le fichiers hce.csv et creer un DataFrame](#toc0_)
<!-- ![MolecularDimension.png](attachment:MolecularDimension.png) -->
![MolecularDimension.png](./Graphics/Pandas.jpg)

In [1]:
import pandas.util  # Assuming 'util' is an alias for pandas.util
import pandas as pd
# Read the CSV file
df1 = pd.read_csv("Patrick_GDB-9_dataframe.csv")
df1
# Filter rows with pce_1 > 10

,smiles_key,smiles,smiles_c,HOMO(HARTREE),LUMO(HARTREE),gap(HARTREE),HOMO(eV),LUMO(eV),gap(eV)
0,gdb 1,C,C,-0.3877,0.1171,0.5048,-10.549854,3.186453,13.736308
1,gdb 2,N,N,-0.2570,0.0829,0.3399,-6.993326,2.255824,9.249150
2,gdb 3,O,O,-0.2928,0.0687,0.3615,-7.967494,1.869422,9.836916
3,gdb 4,C#C,C#C,-0.2845,0.0506,0.3351,-7.741639,1.376896,9.118535
4,gdb 5,C#N,C#N,-0.3604,0.0191,0.3796,-9.806984,0.519737,10.329442
...,...,...,...,...,...,...,...,...,...
133880,gdb 133881,C1C2C3C4C5OC14C5N23,C1[C@@H]2[C@@H]3[C@H]4[C@@H]5O[C@]14[C@@H]5N23,-0.2254,0.0588,0.2842,-6.133446,1.600029,7.733476
133881,gdb 133882,C1N2C3C2C2C4OC12C34,C1N2[C@H]3[C@@H]2[C@@H]2[C@H]4O[C@@]12[C@@H]34,-0.2393,0.0608,0.3002,-6.511685,1.654452,8.168858
133882,gdb 133883,C1N2C3C4C5C2C13CN45,C1N2[C@@H]3[C@@H]4[C@@H]5[C@H]2[C@]13CN45,-0.2233,0.0720,0.2953,-6.076302,1.959220,8.035522
133883,gdb 133884,C1N2C3C4C5CC13C2C45,C1N2[C@H]3[C@@H]4[C@@H]5C[C@]13[C@H]2[C@H]45,-0.2122,0.0881,0.3003,-5.774256,2.397323,8.171579
133884,gdb 133885,C1N2C3C4C5OC13C2C45,C1N2[C@H]3[C@@H]4[C@@H]5O[C@]13[C@H]2[C@H]45,-0.2316,0.0742,0.3058,-6.302157,2.019085,8.321242

In [2]:
df=df1.iloc[0:5,:]
my1_df=df
my1_df

,smiles_key,smiles,smiles_c,HOMO(HARTREE),LUMO(HARTREE),gap(HARTREE),HOMO(eV),LUMO(eV),gap(eV)
0,gdb 1,C,C,-0.3877,0.1171,0.5048,-10.549854,3.186453,13.736308
1,gdb 2,N,N,-0.2570,0.0829,0.3399,-6.993326,2.255824,9.249150
2,gdb 3,O,O,-0.2928,0.0687,0.3615,-7.967494,1.869422,9.836916
3,gdb 4,C#C,C#C,-0.2845,0.0506,0.3351,-7.741639,1.376896,9.118535
4,gdb 5,C#N,C#N,-0.3604,0.0191,0.3796,-9.806984,0.519737,10.329442

####  <a id='toc1_3_'></a>[Utilisation de `RDKIT`pour la generer des coordonnees 3D xyz](#toc0_)

<img src="./Graphics/Rdkit.png" width="400"></center>

#### <a id='toc1_1_'></a>[Representation Moleculaire et Descripteurs](#toc0_)
1.**Descripteurs 0D**. Concernant les discripteurs Â«Â CompositionÂ Â», ne fournissent aucune information sur la structure molÃ©culaire ou la connectivitÃ© des atomes.

2.**Descripteurs 1D**. LiÃ© Ã  des ensembles de sous-structures telles que des groupes fonctionnels.

3.**Descripteurs 2D**. FonctionnalitÃ©s fournissant des informations sur la topologie molÃ©culaire basÃ©es sur la reprÃ©sentation graphique des molÃ©cules.

4.**Descripteurs 3D**. CaractÃ©ristiques gÃ©omÃ©triques fournissant des informations sur les coordonnÃ©es spatiales des atomes d'une molÃ©cule.

5.**Descripteurs 4D**. Ã‰galement appelÃ©s **descripteurs basÃ©s sur une grille**, introduisent une quatriÃ¨me dimension caractÃ©risant les interactions entre les molÃ©cules et les sites actifs d'un rÃ©cepteur ou les multiples Ã©tats conformationnels des molÃ©cules.


<!-- ![MolecularDimension.png](attachment:MolecularDimension.png) -->
![MolecularDimension.png](./Graphics/MolecularDimension.png)

In [3]:
from rdkit import Chem
from rdkit.Chem import Draw
#from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import rdDepictor
from rdkit.Chem import AllChem
from pathlib import Path
#IPythonConsole.ipython_3d = True
import py3Dmol

import rdkit
print(rdkit.__version__)

2024.03.3


####  <a id='toc1_3_'></a>[ReprÃ©sentation des molÃ©cules 3D avec py3Dmol ](#toc0_)

In [4]:
# import libraries 
from openbabel import pybel as pb  
from openbabel import openbabel as ob

In [5]:
df

,smiles_key,smiles,smiles_c,HOMO(HARTREE),LUMO(HARTREE),gap(HARTREE),HOMO(eV),LUMO(eV),gap(eV)
0,gdb 1,C,C,-0.3877,0.1171,0.5048,-10.549854,3.186453,13.736308
1,gdb 2,N,N,-0.2570,0.0829,0.3399,-6.993326,2.255824,9.249150
2,gdb 3,O,O,-0.2928,0.0687,0.3615,-7.967494,1.869422,9.836916
3,gdb 4,C#C,C#C,-0.2845,0.0506,0.3351,-7.741639,1.376896,9.118535
4,gdb 5,C#N,C#N,-0.3604,0.0191,0.3796,-9.806984,0.519737,10.329442

####  <a id='toc1_3_'></a>[Utilisation de crest et xTB pour la recherches des conformers](#toc0_)
 <center> <img src = "./Graphics/crest.png" width = "600">
 <img src = "./Graphics/xtb.jpeg" width = "600"> </center>

####  <a id='toc1_3_'></a>[Workflow de Crest et xTB dans la recherches des conformers ](#toc0_)
 <center> <img src = "./Graphics/crestfeatures2.png" width = "600">
 <img src = "./Graphics/workflow.jpeg" width = "600"> </center>

In [6]:
import os, sys
import inspect
from pathlib import Path
import tempfile
from utils import run_command

import rdkit
from rdkit.Chem import AllChem, DataStructs
from rdkit.Chem import AllChem as Chem
from rdkit.Chem import RDConfig
sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))
import sascorer

import numpy as np
import torch
import torch.nn as nn
print(rdkit.__version__)

2024.03.3

In [7]:
MY_OBABEL_DATA = os.path.join(os.getcwd(), 'MY_OBABEL_DATA')
os.makedirs(MY_OBABEL_DATA, exist_ok=True)

In [8]:
def find_homo_lumo(mf_pyscf, au2ev):
    """Function that returns the HOMO and LUMO index and the gap energy in eV

    Args:
        mf_pyscf (pyscf object): pyscf meam-field object of the molecule to be evaluated.
    """
    # Index of HOMO and LUMO
    lumo_idx = mf_pyscf.mo_occ.tolist().index(0.)
    homo_idx = lumo_idx - 1

    # Calculate the gap Homo-LUMO
    E_HOMO = mf_pyscf.mo_energy[homo_idx]*au2ev
    E_LUMO = mf_pyscf.mo_energy[lumo_idx]*au2ev
    E_g = abs(E_HOMO - E_LUMO)

    return E_HOMO, E_LUMO, E_g

In [9]:
pip install dftd4

Requirement already satisfied: dftd4 in /home/mvotokps/anaconda3/envs/tartarus/lib/python3.8/site-packages (3.6.0)
Requirement already satisfied: cffi in /home/mvotokps/anaconda3/envs/tartarus/lib/python3.8/site-packages (from dftd4) (1.16.0)
Requirement already satisfied: numpy in /home/mvotokps/anaconda3/envs/tartarus/lib/python3.8/site-packages (from dftd4) (1.23.5)
Requirement already satisfied: pycparser in /home/mvotokps/anaconda3/envs/tartarus/lib/python3.8/site-packages (from cffi->dftd4) (2.22)

[notice] A new release of pip is available: 24.1 -> 24.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd
import rdkit
from rdkit import Chem
import subprocess as sp
from pyscf import dft,scf,tddft
from pyscf import gto
import re
from pyscf.data import nist
#conversion en eV
au2ev = nist.HARTREE2EV
import dftd4.pyscf as disp
def calculate_properties(df, working_dir):
    """
    Calculates molecular properties for SMILES strings in a DataFrame,
    handling xtb convergence errors and filtering unsuccessful molecules.

    Args:
        df (pandas.DataFrame): A DataFrame containing a "smiles" column.
        working_dir (str): The directory to use for calculations and temporary files.

    Returns:
        pandas.DataFrame: A DataFrame containing calculated properties for successful molecules.
    """
    
    dtb = []
    yesso = ["smiles_key","HOMO_HF(eV)","HOMO_DFT(eV)","HOMO_dftd4(eV)","LUMO_HF(eV)","LUMO_DFT(eV)","LUMO_dftd4(eV)","GAP_HF(eV)", "GAP_DFT(eV)","GAP_dftd4(eV)"]


    filtered_df = df.copy()  # Create a copy to avoid modifying the original DataFrame

    for i in range(len(filtered_df)):
        smiles = filtered_df.loc[i, "smiles"]
        smiles_key = filtered_df.loc[i, "smiles_key"]

        mol = Chem.MolFromSmiles(smiles)
        mol = Chem.AddHs(mol)
        charge = Chem.rdmolops.GetFormalCharge(mol)
        atom_number = mol.GetNumAtoms()

        # Create a single directory for all calculations
        directory = os.path.join(working_dir, smiles_key)
        os.makedirs(directory, exist_ok=True)

        # Change directory for calculations
        os.chdir(directory)
        system = lambda x: run_command(x, verbose=5)

        # Write the smile to a file
        with open('test.smi', 'w') as f:
            f.write(smiles)

        # Prepare the input file
        os.system('obabel test.smi --gen3D -O test.xyz')

        with open('test.xyz', 'r') as f:
            lines = f.readlines()

          #  Supprimer les deux premiÃ¨res lignes
        mol_xtb_xyz = '\n'.join(lines[2:])
        # supression de la premiere ligne (nombre d'atomes) pour les donnees XYZ
        #lines = mol_xtb_xyz.strip().split('\n')
        #mol_xtb_xyz = '\n'.join(lines[1:])

        mol_pyscf = gto.Mole(
            atom=mol_xtb_xyz,
            charge=0,
            spin=0,
            basis="6-31G(2df,p)",
            symmetry=True,
            unit='Angstrom'
        )
        mol_pyscf.build()
        myhf = scf.RHF(mol_pyscf).run()
        mdf = dft.RKS(mol_pyscf, xc="B3LYP").run()
        mdft = mdf.newton()
        mdft = disp.energy(mdft).run() 

        Eks_homo, Eks_lumo, Eks_g = find_homo_lumo(myhf, au2ev)
        Eks1_homo, Eks1_lumo, Eks1_g = find_homo_lumo(mdf, au2ev)
        Ekcc_homo, Ekcc_lumo, Ekcc_g =  find_homo_lumo(mdft, au2ev)


        dtb.append([smiles_key,Eks_homo,Eks1_homo,Ekcc_homo,Eks_lumo,Eks1_lumo,Ekcc_lumo,Eks_g ,Eks1_g ,Ekcc_g ])
        
        os.chdir('..')

    df_ENEGY = pd.DataFrame(dtb, columns=yesso)
    return  df_ENEGY

df_ENEGY= calculate_properties(df, MY_OBABEL_DATA)

converged SCF energy = -40.2024530217032

1 molecule converted

converged SCF energy = -40.5231117291941
converged SCF energy = -40.5231117291941
converged SCF energy = -56.1976545961407

1 molecule converted

converged SCF energy = -56.5591965412214
converged SCF energy = -56.559196541222
converged SCF energy = -76.0249283314661

1 molecule converted

converged SCF energy = -76.4211097207822
converged SCF energy = -76.4211097207824
converged SCF energy = -76.8261338176975

1 molecule converted

converged SCF energy = -77.3333339612085
converged SCF energy = -77.3333339612085
converged SCF energy = -92.8803201960963

1 molecule converted

converged SCF energy = -93.4262041969706
converged SCF energy = -93.4262041969761

WARN: Orbital degeneracy broken

In [13]:
df_ENEGY

,smiles_key,HOMO_HF(eV),HOMO_DFT(eV),HOMO_dftd4(eV),LUMO_HF(eV),LUMO_DFT(eV),LUMO_dftd4(eV),GAP_HF(eV),GAP_DFT(eV),GAP_dftd4(eV)
0,gdb 1,-14.735454,-10.554490,-10.554485,6.950491,3.208619,3.208621,21.685945,13.763109,13.763107
1,gdb 2,-11.539430,-6.928129,-6.928135,6.053193,2.250323,2.250320,17.592624,9.178452,9.178456
2,gdb 3,-13.528920,-7.937455,-7.937461,5.809224,1.852475,1.852472,19.338145,9.789930,9.789933
3,gdb 4,-10.909435,-7.750257,-7.750257,5.843377,1.365924,1.365925,16.752812,9.116182,9.116182
4,gdb 5,-13.264417,-9.755053,-9.755046,5.197987,0.441019,0.441023,18.462404,10.196072,10.196070

In [12]:
df_xtb_mf

       GAP(eV)   HOMO(eV)  LUMO(eV)
0    21.686012 -14.735508  6.950505
1    17.592638 -11.539421  6.053217
2    19.338131 -13.528921  5.809210
3    16.752664 -10.909373  5.843292
4    18.462404 -13.264417  5.197987
..         ...        ...       ...
105  17.363200 -10.920683  6.442517
106  14.135463  -9.716754  4.418709
107  14.327958 -10.568964  3.758994
108  16.890839 -12.947097  3.943742
109  13.688379 -10.225688  3.462691

[110 rows x 3 columns]

In [13]:
df_xtb_dft

       GAP(eV)   HOMO(eV)  LUMO(eV)
0    13.763159 -10.554524  3.208635
1     9.178471  -6.928119  2.250352
2     9.789912  -7.937454  1.852457
3     9.116053  -7.750206  1.365847
4    10.196072  -9.755053  0.441019
..         ...        ...       ...
105   8.187537  -6.374429  1.813108
106   7.024612  -6.865986  0.158626
107   7.019494  -7.579919 -0.560425
108   8.991943  -9.468895 -0.476953
109   5.769021  -6.988373 -1.219351

[110 rows x 3 columns]

In [14]:
DF_dFT=pd.concat([df,df_xtb_dft], axis=1)

In [15]:
DF_dFT

,smiles_key,smiles,smiles_c,HOMO(HARTREE),LUMO(HARTREE),gap(HARTREE),HOMO(eV),LUMO(eV),gap(eV),GAP(eV),HOMO(eV),LUMO(eV)
0,gdb 1,C,C,-0.3877,0.1171,0.5048,-10.549854,3.186453,13.736308,13.763159,-10.554524,3.208635
1,gdb 2,N,N,-0.2570,0.0829,0.3399,-6.993326,2.255824,9.249150,9.178471,-6.928119,2.250352
2,gdb 3,O,O,-0.2928,0.0687,0.3615,-7.967494,1.869422,9.836916,9.789912,-7.937454,1.852457
3,gdb 4,C#C,C#C,-0.2845,0.0506,0.3351,-7.741639,1.376896,9.118535,9.116053,-7.750206,1.365847
4,gdb 5,C#N,C#N,-0.3604,0.0191,0.3796,-9.806984,0.519737,10.329442,10.196072,-9.755053,0.441019
...,...,...,...,...,...,...,...,...,...,...,...,...
105,gdb 106,C1C2CC1O2,C1[C@H]2C[C@@H]1O2,-0.2352,0.0994,0.3346,-6.400118,2.704812,9.104930,8.187537,-6.374429,1.813108
106,gdb 107,C#CCC#C,C#CCC#C,-0.2633,0.0345,0.2978,-7.164758,0.938793,8.103551,7.024612,-6.865986,0.158626
107,gdb 108,C#CCC#N,C#CCC#N,-0.2911,0.0111,0.3022,-7.921234,0.302046,8.223281,7.019494,-7.579919,-0.560425
108,gdb 109,N#CCC#N,N#CCC#N,-0.3494,-0.0151,0.3344,-9.507658,-0.410892,9.099487,8.991943,-9.468895,-0.476953
109,gdb 110,O=CCC#C,O=CCC#C,-0.2583,-0.0337,0.2245,-7.028701,-0.917024,6.108956,5.769021,-6.988373,-1.219351

In [16]:
df4 = pd.DataFrame()
for i in range(len(df)):
    dif_homo= abs(df_xtb_dft.at[i, 'HOMO(eV)'] - df.at[i, 'HOMO(eV)'])
    dif_lumo =abs(df_xtb_dft.at[i, 'LUMO(eV)'] - df.at[i, 'LUMO(eV)'])
    dif_gap = abs(df_xtb_dft.at[i, 'GAP(eV)'] - df.at[i, 'gap(eV)'])
    df4.at[i, 'dif_homo(kcal/mol)'] = dif_homo * 627.5
    df4.at[i, 'dif_lumo(kcal/mol)'] =  dif_lumo * 627.5
    df4.at[i, 'dif_gap(kcal/mol)'] = dif_gap  * 627.5

In [17]:
DF_dFT1=pd.concat([DF_dFT, df4], axis=1)

In [18]:
DF_dFT1

,smiles_key,smiles,smiles_c,HOMO(HARTREE),LUMO(HARTREE),gap(HARTREE),HOMO(eV),LUMO(eV),gap(eV),GAP(eV),HOMO(eV),LUMO(eV),dif_homo(kcal/mol),dif_lumo(kcal/mol),dif_gap(kcal/mol)
0,gdb 1,C,C,-0.3877,0.1171,0.5048,-10.549854,3.186453,13.736308,13.763159,-10.554524,3.208635,2.930010,13.919184,16.849193
1,gdb 2,N,N,-0.2570,0.0829,0.3399,-6.993326,2.255824,9.249150,9.178471,-6.928119,2.250352,40.917685,3.433652,44.351337
2,gdb 3,O,O,-0.2928,0.0687,0.3615,-7.967494,1.869422,9.836916,9.789912,-7.937454,1.852457,18.849779,10.645510,29.495289
3,gdb 4,C#C,C#C,-0.2845,0.0506,0.3351,-7.741639,1.376896,9.118535,9.116053,-7.750206,1.365847,5.375599,6.933641,1.558043
4,gdb 5,C#N,C#N,-0.3604,0.0191,0.3796,-9.806984,0.519737,10.329442,10.196072,-9.755053,0.441019,32.586716,49.395673,83.689904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,gdb 106,C1C2CC1O2,C1[C@H]2C[C@@H]1O2,-0.2352,0.0994,0.3346,-6.400118,2.704812,9.104930,8.187537,-6.374429,1.813108,16.120147,559.543920,575.664066
106,gdb 107,C#CCC#C,C#CCC#C,-0.2633,0.0345,0.2978,-7.164758,0.938793,8.103551,7.024612,-6.865986,0.158626,187.479659,489.554527,677.034186
107,gdb 108,C#CCC#N,C#CCC#N,-0.2911,0.0111,0.3022,-7.921234,0.302046,8.223281,7.019494,-7.579919,-0.560425,214.175271,541.201102,755.376373
108,gdb 109,N#CCC#N,N#CCC#N,-0.3494,-0.0151,0.3344,-9.507658,-0.410892,9.099487,8.991943,-9.468895,-0.476953,24.323755,41.453172,67.484441
109,gdb 110,O=CCC#C,O=CCC#C,-0.2583,-0.0337,0.2245,-7.028701,-0.917024,6.108956,5.769021,-6.988373,-1.219351,25.305941,189.710636,213.309063

In [19]:
# Assuming you have a DataFrame named 'df'
df_xtb_mf.to_csv('my_hf_ob_GDB9.csv', index=False)  # Save without index

DF_dFT1.to_csv('dft_ob_GDB9.csv', index=False)   # Save with index
#df_xtb_md4.to_csv('my_mda_GDB9_ob.csv', index=False)   # Save with index